
POST http://localhost:4000/patients
content-Type:application/json

{
  "name": "Joh Doe kafka test2",
  "email": "kafka3_test@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###